Implemented A* search to solve the puzzle problem

In [12]:
from collections import namedtuple
from random import choice
from tqdm.auto import tqdm
import numpy as np

In [ ]:
import numpy as np
import heapq
from collections import namedtuple
from tqdm.auto import tqdm
from random import choice

PUZZLE_DIM = 5
RANDOMIZE_STEPS = 100_000
action = namedtuple('Action', ['pos1', 'pos2'])

def available_actions(state: np.ndarray) -> list['Action']:
    x, y = [int(_[0]) for _ in np.where(state == 0)]
    actions = list()
    if x > 0:
        actions.append(action((x, y), (x - 1, y)))
    if x < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x + 1, y)))
    if y > 0:
        actions.append(action((x, y), (x, y - 1)))
    if y < PUZZLE_DIM - 1:
        actions.append(action((x, y), (x, y + 1)))
    return actions

def do_action(state: np.ndarray, action: 'Action') -> np.ndarray:
    new_state = state.copy()
    new_state[action.pos1], new_state[action.pos2] = new_state[action.pos2], new_state[action.pos1]
    return new_state

#randomization
state = np.array([i for i in range(1, PUZZLE_DIM**2)] + [0]).reshape((PUZZLE_DIM, PUZZLE_DIM))
for _ in tqdm(range(RANDOMIZE_STEPS), desc='Randomizing'):
    state = do_action(state, choice(available_actions(state)))

#Heuristic functions
def manhattan_distance(state: np.ndarray, goal_state: np.ndarray) -> int:
    total_distance = 0
    for val in range(1, PUZZLE_DIM**2):
        current_pos = np.argwhere(state == val)[0]
        goal_pos = np.argwhere(goal_state == val)[0]
        total_distance += abs(current_pos[0] - goal_pos[0]) + abs(current_pos[1] - goal_pos[1])
    return total_distance

# Here I implemented A* search
def solve_n2_1_puzzle(initial_state: np.ndarray, goal_state: np.ndarray, heuristic_func, length_criteria=0) -> list:
    pq = []
    heapq.heappush(pq, (heuristic_func(initial_state, goal_state), 0, [], initial_state))
    visited = set()

    while pq:
        _, move_count, path, current_state = heapq.heappop(pq)
        if np.array_equal(current_state, goal_state):
            return path, current_state
        state_tuple = tuple(current_state.flatten())
        if state_tuple in visited:
            continue
        visited.add(state_tuple)

        for act in available_actions(current_state):
            new_state = do_action(current_state, act)
            new_path = path + [act]
            new_priority = heuristic_func(new_state, goal_state) + length_criteria * len(new_path)
            heapq.heappush(pq, (new_priority, len(new_path), new_path, new_state))

    return None, None

goal_state = np.array([i for i in range(1, PUZZLE_DIM**2)] + [0]).reshape((PUZZLE_DIM, PUZZLE_DIM))
solution, final_state = solve_n2_1_puzzle(state, goal_state, manhattan_distance)

if solution:
    print(f"Solution found in {len(solution)} moves.")
    print("Final state:")
    print(final_state)
    print("Moves:")
    for move in solution:
        print(move)
else:
    print("No solution found.")


Randomizing:   0%|          | 0/100000 [00:00<?, ?it/s]

Solution found in 380 moves.
Final state:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24  0]]
Moves:
Action(pos1=(0, 2), pos2=(0, 1))
Action(pos1=(0, 1), pos2=(1, 1))
Action(pos1=(1, 1), pos2=(1, 2))
Action(pos1=(1, 2), pos2=(1, 3))
Action(pos1=(1, 3), pos2=(0, 3))
Action(pos1=(0, 3), pos2=(0, 2))
Action(pos1=(0, 2), pos2=(0, 1))
Action(pos1=(0, 1), pos2=(1, 1))
Action(pos1=(1, 1), pos2=(1, 2))
Action(pos1=(1, 2), pos2=(2, 2))
Action(pos1=(2, 2), pos2=(2, 1))
Action(pos1=(2, 1), pos2=(3, 1))
Action(pos1=(3, 1), pos2=(3, 2))
Action(pos1=(3, 2), pos2=(4, 2))
Action(pos1=(4, 2), pos2=(4, 1))
Action(pos1=(4, 1), pos2=(4, 0))
Action(pos1=(4, 0), pos2=(3, 0))
Action(pos1=(3, 0), pos2=(3, 1))
Action(pos1=(3, 1), pos2=(3, 2))
Action(pos1=(3, 2), pos2=(3, 3))
Action(pos1=(3, 3), pos2=(4, 3))
Action(pos1=(4, 3), pos2=(4, 2))
Action(pos1=(4, 2), pos2=(3, 2))
Action(pos1=(3, 2), pos2=(3, 3))
Action(pos1=(3, 3), pos2=(3, 4))
Action(pos1=(3, 4), pos2=(2, 4))
Ac